name: Get GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get GitHub secrets
        env:
          secret_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host_name: ${{ secrets.HOSTNAME }}
          user_name: ${{ secrets.USER_NAME }}
        run: |
          echo "$secret_key" > web-php-server.pem
          chmod 400 web-php-server.pem
          cat web-php-server.pem | echo
          echo "The value of host name is $host_name"
          echo "The value of user name is $user_name"

      - name: get values in next step
        run: |
          echo "The value of host name is $host_name"
          echo "The value of user name is $user_name"
