name: Get GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub secrets
        env:
          SECRET_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "The value of secret key is ${{ secrets.SSH_PRIVATE_KEY }}"
