name: Get GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get GitHub secrets
        env:
          secret_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host_name: ${{ secrets.HOSTNAME }}
          user_name: ${{ secrets.USER_NAME }}
        run: |
          echo "$secret_key" > web-php-server.pem
          chmod 400 web-php-server.pem
          # read the file contents
          ssh -o StrictHostKeyChecking=no -i web-php-server.pem ${user_name}@${host_name} '
          #Now we have got the access of EC2 and we will start the deploy
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519_naveed
          cd /var/www/html/cicd-training &&
          git checkout main &&
          git reset --hard origin/main &&
          git pull origin main
          '
          echo "Deployment commands run successfully"
