name: CI/CD Testing for vue project

on:
  push:
    branches: [ main ]

jobs:
  #First we will log into ec2 and take pull of main , then we will deploy in EC2
  take-pull:
    name: taking-pull-of-main-branch
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: checkout-actions
        uses: actions/checkout@v3

      - name: setup-node-for-use-with-actions-step-name
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: login-to-ec2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > web-php-server.pem
          chmod 400 web-php-server.pem
          echo "permissions set"
          echo "ppk=$PRIVATE_KEY" >> $GITHUB_ENV
          echo "$ppk"
          ssh -i web-php-server.pem ubuntu@13.213.156.49
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /var/www/html/cicd-training &&
            git checkout main &&
            git reset --hard origin/main &&
            git pull origin main &&
            nvm use 14 &&
            npm run build
          '
          
